### ISSUE TITLE
Add ability to provide basic auth

### ISSUE THREAD

**Issue by emars** [searchkit/searchkit-express#3]
I'm using elasticsearch on compose.io which requires me to use HTTP authorization for requests to elastic search.

I'll submit a PR enabling Basic Auth to the proxy.

**Comment by emars** [comment]
Actually this was solved by including the auth credentials in the `host` parameter:

```
config: {
    host: 'https://username:password@[elasticsearch-url]`
}
```

**Comment by joemcelroy** [comment]
Would be good if you could PR an example in the docs so doesn't catch anyone else,

**Comment by infacq** [comment]
@emars could you add this in the docs

**Comment by emars** [comment]
I added it in PR #4.

https://github.com/searchkit/searchkit-express/pull/4/commits/abd5a28c0b70ed6b80a5d6493b4a43801f42e199
