### ISSUE TITLE
Getting error on first launch

### ISSUE THREAD

**Issue by armsofter** [searchkit/searchkit-express#6]
The error that i am getting

![capture](https://cloud.githubusercontent.com/assets/8417675/24245704/5bafeba6-0fdd-11e7-95b3-370803424abe.PNG)

and my code is this:

import express from "express";
var app = express();
import '../../App.css';
import {
	SearchkitManager,
	SearchkitProvider,
	Layout,
	InitialLoader,
	Pagination,
	HitsStats,
	TopBar,
	SelectedFilters,
	ResetFilters,
	LayoutBody,
	LayoutResults,
	ActionBarRow,
	ActionBar,
	ViewSwitcherToggle,
	ViewSwitcherHits,
	NoHits} from "searchkit";

import React  from 'react';
import {MovieHitsGridItem, MovieHitsListItem, SearchArea} from "../../ResultComponents"
const searchkit = new SearchkitManager("my ip address",{});

**Comment by ssetem** [comment]
are you trying to do serverside rendering?

**Comment by armsofter** [comment]
Yes and I am using react-searchkit for my project.

**Comment by ssetem** [comment]
yeh currently serverside rendering is on our todo list, hopefully get get something in beta soon
